# Generated by Django 5.1.2 on 2024-11-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('arquivo', models.FileField(upload_to='documentos/')),
                ('tipo_documento', models.CharField(choices=[('acordao', 'Acórdão'), ('decisao', 'Decisão'), ('despacho', 'Despacho')], max_length=20)),
                ('tipo_processo', models.CharField(choices=[('concentracao', 'Ato de Concentração'), ('administrativo', 'Processo Administrativo')], max_length=20)),
                ('setor', models.CharField(choices=[('energia', 'Energia'), ('telecom', 'Telecomunicações'), ('transporte', 'Transporte')], max_length=20)),
                ('ano', models.IntegerField()),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data_upload'],
            },
        ),
    ]
